"""Keep the standalone Colab depth service and launch guide in sync with source."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / 'control/vla_bridge/policy_server.ipynb'

def sync():
    notebook = json.loads(NOTEBOOK.read_text())
    server = (ROOT / 'control/vla_bridge/fastfs_server.py').read_text()
    for cell in notebook['cells']:
        if cell.get('id') == 'resident-fastfs-source':
            cell['source'] = ('%%writefile /content/fastfs_server.py\n' + server).splitlines(keepends=True)
            cell['outputs'] = []
            cell['execution_count'] = None
    NOTEBOOK.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + '\n')
    parts = ['<!-- Generated by scripts/sync_policy_notebook.py; edit the notebook/source, then regenerate. -->\n']
    for cell in notebook['cells']:
        source = ''.join(cell.get('source', []))
        parts.append(source if cell['cell_type'] == 'markdown' else '```python\n' + source.rstrip() + '\n```')
    (ROOT / 'control/vla_bridge/policy_server_launch.md').write_text('\n\n'.join(parts) + '\n')

if __name__ == '__main__':
    sync()
