"""Standalone diagnostic CLI: independently verify So-101/So-101.urdf against TWIN-01..05.

This is the phase's automated acceptance gate: it loads `So-101/So-101.urdf`
(the artifact generated by `scripts/mjcf_to_urdf.py`, Phase 10 Plan 10-03)
through `yourdfpy` -- a standard, independent URDF parser -- rather than
trusting the generator's own output, and confirms:
  - the gripper (`right_gripper`) is correctly chained under the wrist
    (`right_hand`), not a disconnected root-level body (TWIN-01)
  - `wrist_roll` is present with the correct asymmetric mechanical-limit
    range (TWIN-02)
  - `gripper_left`/`gripper_right` are prismatic with the correct axes
    (TWIN-03)
  - no mesh filename is an absolute path (TWIN-04)

Usage:
    python scripts/verify_urdf.py

This is diagnostic, not production code -- mirrors
`diagnostics/measure_object_depth.py`'s print-checkmark-or-warning idiom:
when run standalone this script never raises past its own precondition
check, failures are `⚠`-flagged text only (exit code 0). The pytest-based
pass/fail assertions live in `scripts/test_verify_urdf.py`, which imports
the helper functions below rather than duplicating this logic.
"""
from pathlib import Path

import yourdfpy

ROOT = Path(__file__).resolve().parent.parent
URDF_PATH = ROOT / "So-101" / "So-101.urdf"

# TWIN-02: wrist_roll's exact asymmetric mechanical-limit range, per
# robot.xml's `wrist_roll` joint (re-derived from live calibration, see
# Phase 10 D-06/Pitfall 1 -- NOT the naive full-turn placeholder).
WRIST_ROLL_LOWER = -2.7438472969992493
WRIST_ROLL_UPPER = 2.841206309382605


def load_generated_urdf() -> yourdfpy.URDF:
    """Load `So-101/So-101.urdf` via yourdfpy.

    Raises SystemExit pointing at the fix (regenerate the URDF) if the file
    doesn't exist yet.
    """
    if not URDF_PATH.exists():
        raise SystemExit(
            f"ERROR: {URDF_PATH} not found. Run scripts/mjcf_to_urdf.py first "
            "to generate it."
        )
    return yourdfpy.URDF.load(
        str(URDF_PATH), load_meshes=False, build_collision_scene_graph=False
    )


def build_parent_map(robot: yourdfpy.URDF) -> dict:
    """dict[child_link_name] -> (joint_name, parent_link_name), built from
    robot.joint_map.values()'s .parent/.child/.name attributes."""
    parent_map = {}
    for joint in robot.joint_map.values():
        parent_map[joint.child] = (joint.name, joint.parent)
    return parent_map


def is_descendant(robot: yourdfpy.URDF, link_name: str, ancestor_name: str) -> bool:
    """Walk build_parent_map upward from link_name until ancestor_name is
    found or the chain runs out of parents (root link reached)."""
    parent_map = build_parent_map(robot)
    current = link_name
    seen = set()
    while current in parent_map:
        if current in seen:
            # Cycle guard -- should never happen in a valid kinematic tree.
            return False
        seen.add(current)
        _, parent = parent_map[current]
        if parent == ancestor_name:
            return True
        current = parent
    return False


def no_absolute_mesh_paths(robot: yourdfpy.URDF) -> list:
    """Return a list of any mesh filename strings starting with '/' or
    'file://' across every link's visual and collision geometry. Empty list
    = pass (TWIN-04)."""
    bad = []
    for link in robot.link_map.values():
        for visual in link.visuals or []:
            mesh = visual.geometry.mesh if visual.geometry is not None else None
            if mesh is not None and mesh.filename and (
                mesh.filename.startswith("/") or mesh.filename.startswith("file://")
            ):
                bad.append(mesh.filename)
        for collision in link.collisions or []:
            mesh = collision.geometry.mesh if collision.geometry is not None else None
            if mesh is not None and mesh.filename and (
                mesh.filename.startswith("/") or mesh.filename.startswith("file://")
            ):
                bad.append(mesh.filename)
    return bad


def main() -> None:
    robot = load_generated_urdf()

    # TWIN-01: gripper is a descendant of the wrist (right_hand), not a
    # disconnected root-level body.
    if is_descendant(robot, "right_gripper", "right_hand"):
        print("✓ gripper (right_gripper) is a descendant of right_hand (wrist)")
    else:
        print("⚠ gripper (right_gripper) is NOT a descendant of right_hand (wrist)")

    # TWIN-02: wrist_roll present, revolute, with the expected asymmetric range.
    wrist_roll = robot.joint_map.get("wrist_roll")
    if wrist_roll is not None and wrist_roll.type == "revolute":
        lo, hi = wrist_roll.limit.lower, wrist_roll.limit.upper
        if abs(lo - WRIST_ROLL_LOWER) < 1e-6 and abs(hi - WRIST_ROLL_UPPER) < 1e-6:
            print(f"✓ wrist_roll present, revolute, range ({lo}, {hi})")
        else:
            print(f"⚠ wrist_roll range mismatch: got ({lo}, {hi})")
    else:
        print("⚠ wrist_roll missing or not a revolute joint")

    # TWIN-03: gripper_left/gripper_right prismatic with correct axes.
    gripper_left = robot.joint_map.get("gripper_left")
    gripper_right = robot.joint_map.get("gripper_right")
    axes_ok = (
        gripper_left is not None
        and gripper_left.type == "prismatic"
        and list(gripper_left.axis) == [0, 1, 0]
        and gripper_right is not None
        and gripper_right.type == "prismatic"
        and list(gripper_right.axis) == [0, -1, 0]
    )
    if axes_ok:
        print("✓ gripper_left/gripper_right prismatic with correct axes")
    else:
        print("⚠ gripper_left/gripper_right missing, wrong type, or wrong axes")

    # TWIN-04: no absolute mesh paths.
    bad_meshes = no_absolute_mesh_paths(robot)
    if not bad_meshes:
        print("✓ no absolute mesh paths")
    else:
        print(f"⚠ absolute mesh paths found: {bad_meshes}")


if __name__ == "__main__":
    main()
